project_name         = "hotel"
environment          = "uat"
cluster_version      = "1.34"
network_state_bucket = "example-hotel-tfstate"
network_state_key    = "uat/stacks/network/terraform.tfstate"
state_region         = "ap-southeast-1"
