project_name         = "hotel"
environment          = "dev"
cluster_version      = "1.29"
network_state_bucket = "example-hotel-tfstate"
network_state_key    = "dev/stacks/network/terraform.tfstate"
state_region         = "ap-southeast-1"
