name: Terraform Governance

on:
  pull_request:
    paths:
      - "terraform/**"
      - "policy/**"
      - ".github/workflows/terraform-governance.yml"

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack:
          - terraform/stacks/network
          - terraform/stacks/platform-eks
          - terraform/stacks/data
          - terraform/stacks/edge
          - terraform/stacks/observability

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init (no backend)
        working-directory: ${{ matrix.stack }}
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: ${{ matrix.stack }}
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        working-directory: terraform
        run: tflint --recursive

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform

      - name: Install Conftest
        run: |
          curl -sSL https://raw.githubusercontent.com/open-policy-agent/conftest/master/install.sh | sh
          sudo mv conftest /usr/local/bin/conftest


      - name: Run OPA policy checks
        run: conftest test $(git ls-files '${{ matrix.stack }}/**/*.tf') --parser hcl2 --policy policy/terraform
